/*CUSTOMER ARE THE CUSTUMER OF OUR PRODUCTS
/CREATE UNIQUE SEQUENCE CUSTOMUR_ID_SEQ;*/

CREATE TABLE CUSTOMERS(
	CUSTOMER_ID INT NOT NULL AUTO_INCREMENT, 
	CUSTOMER_NAME VARCHAR(50),
	CUSTOMER_SURNAME VARCHAR(50),
	ADDRESS VARCHAR(100),
	PRIMARY KEY(CUSTOMER_ID)
);

/*PRODUCTS ARE THE PRODUCTS THAT WE CAN SELL IN OUR SHOP
/CREATE UNIQUE SEQUENCE PRODUCT_ID_SEQ;*/

CREATE TABLE PRODUCTS(
	PRODUCT_NAME VARCHAR(50),
	COMPONENT_LIST VARCHAR(100),
	PRICE INT,
	PRIMARY KEY(PRODUCT_NAME)
);

/*COMPONENTS OF OUR PRODUCS THAT WE CAN SELL IN OUR SHOP
/CREATE UNIQUE SEQUENCE COMPUNENTS_ID_SEQ;*/

CREATE TABLE COMPONENTS(
	COMPONENT_NAME VARCHAR(50),
	AMOUNT INT,
	PRIMARY KEY(COMPONENT_NAME)
);

/*ORDER TABLE THAT INCLUDES ALL ORDERS BY OUR CUSTOMERS*/
CREATE TABLE ORDERS(
	ORDER_ID INT NOT NULL AUTO_INCREMENT,
	CUSTOMER_ID int NOT NULL,
	PRODUCTS varchar(100),
    TOTAL_PRICE int,
	PRIMARY KEY(ORDER_ID),
    FOREIGN KEY(CUSTOMER_ID) REFERENCES customers(CUSTOMER_ID)
);

INSERT INTO CUSTOMERS(CUSTOMER_NAME, CUSTOMER_SURNAME, ADDRESS) VALUES ('Vahid','Abbasi','Sweden');
INSERT INTO CUSTOMERS(CUSTOMER_NAME, CUSTOMER_SURNAME, ADDRESS) VALUES ('Deha','Nemutlu','Sweden');
INSERT INTO CUSTOMERS(CUSTOMER_NAME, CUSTOMER_SURNAME, ADDRESS) VALUES ('Burak','Ozmen','Sweden');

INSERT INTO PRODUCTS  VALUES ('pizza','5 olive, 2 lettuce', 250);
INSERT INTO PRODUCTS  VALUES ('salad','3 lettuce, 5 olive, 1 tomato', 300);
INSERT INTO PRODUCTS  VALUES ('computer','1 HDD, 1 keyboard, 1 mouse', 1000);

INSERT INTO COMPONENTS VALUES ('olive',10);
INSERT INTO COMPONENTS VALUES ('lettuce', 3);
INSERT INTO COMPONENTS VALUES ('HDD',3);
INSERT INTO COMPONENTS VALUES ('keyboard', 3);
INSERT INTO COMPONENTS VALUES ('mouse',3);